# This is a basic workflow to help you get started with Actions

name: hello world javascript github action workflow

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "helloworldaction"
  helloworld:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Run hello world javascript action
      - name: Run hello world javascript action
        uses: jaymit-sg/hello-world-javascript-action@main
        with:
          who-to-greet: 'Jaymit'
